POST  http://127.0.0.1:5000/openai/files?api-version=2023-07-01-preview
Content-Type: application/x-www-form-urlencoded

purpose=batch


###
POST  http://127.0.0.1:5000/openai/files?api-version=2023-07-01-preview
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="purpose"

batch
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="batch_test.jsonl"
Content-Type: text/plain

< ./batch_test.jsonl
------WebKitFormBoundary7MA4YWxkTrZu0gW--